-- ==========================================
-- Hamburguesería OS - Script de Semilla (Seed) para Validación
-- OBSOLETO: Este script fue reemplazado por datos en setup.sql
-- Mantenido solo para referencia histórica
-- ==========================================
-- NOTA: Los datos de prueba ahora están en setup.sql en la sección SEED DATA
-- Ya no es necesario ejecutar este script por separado